# Generated by Django 4.0.6 on 2022-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[(0, 'paid'), (1, 'pending'), (2, 'not sucess')], default='paid', max_length=200, null=True),
        ),
    ]
