# Generated by Django 4.0.6 on 2022-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[(0, 'paid'), (1, 'pending'), (2, 'failed')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.IntegerField(null=True),
        ),
    ]
