# Generated by Django 4.0.6 on 2022-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[(0, 'deposit')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
