# Generated by Django 4.0.6 on 2022-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_wallet_alter_payment_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
