# Generated by Django 4.0.6 on 2022-08-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_type',
        ),
    ]
