# Generated by Django 4.0.6 on 2022-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.IntegerField(null=True),
        ),
    ]
