# Generated by Django 4.0.6 on 2022-08-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
    ]
