# Generated by Django 4.0.6 on 2022-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type_of_seats',
            field=models.CharField(choices=[(0, 'first class'), (1, 'business'), (2, 'economy')], max_length=200, null=True),
        ),
    ]
