# Generated by Django 4.0.6 on 2022-07-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('flight_name', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=100)),
                ('seats_available', models.IntegerField()),
                ('plane_name', models.CharField(max_length=150)),
                ('time_of_departure', models.DateTimeField()),
                ('time_of_arrival', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
