# Generated by Django 4.0.6 on 2022-07-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flights_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
