# Generated by Django 4.0.6 on 2022-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_changed_password',
            field=models.BooleanField(default=True),
        ),
    ]
